### ISSUE TITLE
add ensime-vim support

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-docker#2]
i.e. all this should be in the image https://github.com/ensime/ensime-vim/blob/master/.drone.yml#L5

will speed up the CI runs for ensime-vim

@yazgoo

**Comment by hkupty** [comment]
could be a separate tag, such as `ensime/ensime:ci` this would keep coveralls out of default image

**Comment by fommil** [comment]
@hkupty why would we bother doing that?

**Comment by hkupty** [comment]
This way non-test/ci related usage would not carry unnecessary dependencies - or should I need python-coveralls to run the ensime docker container on my machine?

**Comment by fommil** [comment]
that's complicated. Unless this module is multi GB, let's just add it to the base image.

**Comment by hkupty** [comment]
I fail to see whats complicated in having a separate file including the dependencies instead of adding in the same file, but either way, I'm not maintaining the project, it's your call..

**Comment by fommil** [comment]
is this something you're actually looking in to? Because I don't think the Vim tests are even passing yet and until they get green lights, I don't even want to think about this ticket.

**Comment by hkupty** [comment]
Hum, If this is not a current issue, then I'm actually more interested in having vim tests passing, as my goal is to have a better ensime/neovim experience as a whole.. Sorry for the noise

**Comment by fommil** [comment]
Yup getting the vim tests going green would be awesome! This is just a CI optimisation.

**Comment by hkupty** [comment]
I'm trying to set it up on my machine, hopefully I'll come up with a PR in a near time
